# -*- coding: utf-8 -*-
"""FINE TUNING QWEN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EJb7aR7VBw-80Q6c0qWJNFaBlwUndxv
"""

!pip install -q torch transformers peft trl datasets accelerate bitsandbytes

import json
from datasets import load_dataset, Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig
import torch

BASE_MODEL = "Qwen/Qwen2.5-7B-Instruct"
DATA_PATH = "/content/astrology_chats_fixed.jsonl"
OUTPUT_DIR = "qwen-astrologer-lora"
MAX_SEQ_LEN = 1024
NUM_EPOCHS = 3
LR = 2e-4
BATCH_SIZE = 1
GRAD_ACCUM = 16

##1. Helper: convert ShareGPT-style export to the format this script wants
def convert_sharegpt(in_path: str, out_path: str, system_prompt: str):


  """Run this once if your drive data is in ShareGPT format:
  [{"from": "human", "value": "..."}, {"from": "gpt", "value": "..."}]
  """
  role_map = {"human": "user", "gpt": "assistant", "system": "system"}
  with open(in_path, "r", encoding="utf-8") as f_in, \
        open(out_path, "w", encoding="utf-8") as f_out:
          for line in f_in:
            row = json.loads(line)
            convo = row.get("conversations", row.get("conversation", []))
            msgs = [{"role": "system", "content": system_prompt}]
            for turn in convo:
                role = role_map.get(turn.get("from"), turn.get("from"))
                msgs.append({"role": role, "content": turn.get("value", "")})
            f_out.write(json.dumps({"conversations": msgs}, ensure_ascii=False) + "\n")

SYSTEM_PROMPT = (
    "You are an expert Vedic astrologer. You know how to read a birth chart "
    "(kundli), you speak warmly and empathetically, and when asked for a "
    "prediction you first ask for accurate birth details (date, time, place) "
    "before analysing the kundli."
)

##LOADING TOKENIZER
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
tokenizer.pad_token = tokenizer.pad_token or tokenizer.eos_token


def format_example(example):
    text = tokenizer.apply_chat_template(
        example["messages"], tokenize=False, add_generation_prompt=False
    )
    return {"text": text}

raw_ds = load_dataset("json", data_files=DATA_PATH, split="train")
ds = raw_ds.map(format_example, remove_columns=raw_ds.column_names)

# Simple train/eval split
ds = ds.train_test_split(test_size=0.1, seed=42)
train_ds, eval_ds = ds["train"], ds["test"]

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)
model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                     "gate_proj", "up_proj", "down_proj"],
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

sft_config = SFTConfig(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUM,
    num_train_epochs=NUM_EPOCHS,
    learning_rate=LR,
    logging_steps=10,
    save_strategy="epoch",
    eval_strategy="epoch",
    bf16=True,
    max_length=MAX_SEQ_LEN,
    dataset_text_field="text",
    report_to="none",
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False}
)

trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=train_ds,
    eval_dataset=eval_ds,
    processing_class=tokenizer,
)

trainer.train()

trainer.save_model(OUTPUT_DIR)          # saves LoRA adapter
tokenizer.save_pretrained(OUTPUT_DIR)

# Merge LoRA into base weights so vLLM can load a normal HF model dir
merged_model = model.merge_and_unload()
merged_model.save_pretrained(f"{OUTPUT_DIR}-merged", safe_serialization=True)
tokenizer.save_pretrained(f"{OUTPUT_DIR}-merged")

print("Done. Merged model ready at:", f"{OUTPUT_DIR}-merged")